//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA_Proyecto
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ProyectoDawEntities : DbContext
    {
        public ProyectoDawEntities()
            : base("name=ProyectoDawEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Donacion> Donacion { get; set; }
        public virtual DbSet<Donante> Donante { get; set; }
        public virtual DbSet<Personas_extrema_pobreza> Personas_extrema_pobreza { get; set; }
        public virtual DbSet<Triaje_Digital> Triaje_Digital { get; set; }
        public virtual DbSet<Usuario_Administrativo> Usuario_Administrativo { get; set; }
    }
}
